name: RTD-Precommit
# If _config.yml changes, need to update conf.py
# https://jupyterbook.org/publish/readthedocs.html

on:
  pull_request:
    paths:
      - 'book/_config.yml'

jobs:
  check_conf_py:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Get changed files using defaults
      id: changed-files
      uses: tj-actions/changed-files@v12.2

    - name: Convert _config.yml to conf.py
      if: contains(steps.changed-files.outputs.modified_files, "conf.py") == false
      run: |
        echo "Converting jupyterbook _config.yml to sphinx conf.py for read-the-docs"
        echo "::set-output name=missing_conf::true"

  commit_conf_py:
    needs: check_conf_py
    runs-on: ubuntu-20.04
    if: ${{needs.check_conf_py.outputs.missing_conf}}
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'

    - run: pip install -r requirements.txt

    - name: Generate conf.py
      run: |
        jupyter-book config sphinx book/

    - name: Commit conf.py
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: "add book/conf.py"
        add: book/conf.py
